[package]
name = "pixel"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11"
error-iter = "0.4"
log = "0.4"
winit = "0.29"
winit_input_helper = "0.16"
pixels = "0.15.0"
rand = "0.9.0"
nalgebra = "0.33.2"
colorgrad = "0.7.0"
